name: epc_qr_code
description: >-
  An EPC QR code generation library for Dart and Flutter.
  Create and validate the EPC string content for the QR code.
version: 1.0.0
repository: https://github.com/dufguix/dart_epc

environment:
  sdk: ^3.5.4

dependencies:
  convert: ^3.1.2

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
